apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projecttemplate-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projecttemplate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projecttemplate
  template:
    metadata:
      labels:
        app: projecttemplate
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: "kubernetes.io/arch"
                  operator: In
                  values: ["amd64"]
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: app
        image: {{ .Values.werf.image.app }}
        ports:
        - containerPort: 3000
        env:
        {{- range $name, $value := .Values.env }}
        - name: {{ $name }}
          value: {{ $value | quote }}
        {{- end }}
        volumeMounts:
        - name: projecttemplate
          mountPath: /var/apps/projecttemplate
          subPath: var
        - name: secret-volume
          readOnly: true
          subPath: ".env"
          mountPath: "/app/.env"
      volumes:
      - name: projecttemplate
        persistentVolumeClaim:
          claimName: projecttemplate-pvc
      - name: secret-volume
        secret:
          secretName: projecttemplate-secret
