name: Staging Deployment
on:
  push:
    branches: [sandbox]
jobs:

  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to Registry
        uses: docker/login-action@v2
        with:
          #registry: registry.gitlab.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Install werf
        uses: werf/actions/install@v1.2

      - name: Run script
        run:
          werf converge
        env:
          WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64_SANDBOX }}
          WERF_ENV: sandbox
          WERF_VALUES_ENV: .helm/values-sandbox.yaml
          WERF_REPO: registry.gitlab.com/iconicompany/projecttemplate
          #WERF_REPO: docker.io/iconicompany/projecttemplate
          WERF_SECRET_KEY: ${{ secrets.WERF_SECRET_KEY }}
